messages:
  prefix: "&7[&aPnSeen&7] "
  no-permission: "&c你没有权限使用此命令。"
  reload-success: "&a配置文件已重载。"
  usage-seen: "&c用法: /seen <玩家名|UUID>"
  usage-reload: "&c用法: /pnseen reload"
  player-not-found: "&c未找到该玩家。"
  info:
    name: "&f玩家名：&a%name%"
    uuid: "&f玩家UUID：&a%uuid%"
    playtime: "&f玩家累计在线时间：&a%playtime%"
    offline: "&f玩家离线了 &a%offline%&f（玩家上线了 &a%online%&f）"
    online: "&f玩家上线了 &a%online%"
    location: "&f玩家位置: &a%x% %y% %z% (%world%)"
    ip: "&f玩家IP: &a%ip%"
