name: PnSeen
main: com.pn86.pnseen.PnSeenPlugin
version: 1.0.0
api-version: '1.21'
author: Pn86
commands:
  seen:
    description: 查看玩家信息
    usage: /seen <玩家名|UUID>
    permission: pnseen.use
  pnseen:
    description: PnSeen 管理命令
    usage: /pnseen reload
    permission: pnseen.use
permissions:
  pnseen.use:
    description: 允许使用 /seen 与 /pnseen reload
    default: op
