name: PnVIP
main: com.pn86.pnvip.PnVipPlugin
version: 1.0.0
api-version: '1.21'
author: Pn86
commands:
  vip:
    description: 查看自己的会员信息
    usage: /vip
    permission: pnvip.player
  vipsignin:
    description: 会员签到
    usage: /vipsignin
    permission: pnvip.player
  pnvip:
    description: PnVIP 管理命令
    usage: /pnvip <reload|add|remove|clear>
    permission: pnvip.admin
permissions:
  pnvip.player:
    default: true
  pnvip.admin:
    default: op

softdepend:
  - PlaceholderAPI
