name: PnExtremeSurvival
version: 1.0.0
main: cn.pn86.pnextremesurvival.PnExtremeSurvivalPlugin
api-version: '1.21'
author: Pn86
commands:
  join:
    description: Join game participants
  leave:
    description: Leave game participants
  pnes:
    description: Admin command for PnExtremeSurvival
permissions:
  pnes.admin:
    default: op
