name: PnGoldProspecting
version: 1.0.0
main: com.pn86.pngoldprospecting.PnGoldProspectingPlugin
api-version: '1.21'
authors: [ Pn86 ]
commands:
  pngp:
    description: PnGoldProspecting admin command
    usage: /pngp
    permission: pngp.admin
permissions:
  pngp.admin:
    default: op
