max-level: 100
initial-level: 1
initial-exp: 0

level-exp:
  fixed: 300 # 所有等级升级统一需要经验，设置后优先生效
  default: 100 # 兼容旧模式（fixed<=0时生效）
  increment: 0
  custom: {}

level-tags:
  '1-10': '&7☆ '
  '11-20': '&f★ '
  '21-50': '&6✦ '
  '51-100': '&c✪ '

menu:
  return-command: "spawn"
