name: PnLevel
version: 1.0.0
main: cn.pn86.pnlevel.PnLevelPlugin
api-version: '1.21'
author: Pn86
softdepend: [PlaceholderAPI]
commands:
  pnlv:
    description: PnLevel admin command
    usage: /pnlv <reload|list|look|set|add|remove|reset>
    permission: pnlevel.admin
  level:
    description: View your level info
    usage: /level
  leveltop:
    description: Open level top menu
    usage: /leveltop
  levelgift:
    description: Open or claim level gift
    usage: /levelgift [get]
permissions:
  pnlevel.admin:
    default: op
