name: PnMoneyShop
version: 1.0.0
main: uno.mcme.pnmoneyshop.PnMoneyShopPlugin
api-version: '1.21'
author: Pn86
softdepend:
  - PlaceholderAPI
commands:
  pnms:
    description: PnMoneyShop 命令
    usage: /pnms <reload|buy>
permissions:
  pnmoneyshop.admin:
    description: PnMoneyShop 管理权限
    default: op
  pnmoneyshop.use:
    description: PnMoneyShop 使用权限
    default: true
